import type { Config } from "tailwindcss";
import daisyui from "daisyui";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/layouts/**/*.{js,ts,jsx,tsx,mdx}",
    "global.d.ts",
  ],
  theme: {
    colors: {
      primary: {
        "100": "#EFEBE8",
        "200": "#F3C796",
        "300": "#FFC961",
        "350": "#FAB55A",
        "400": "#FF9B1E",
        "600": "#A35427",
        "700": "#DBBCB4",
        "800": "#D9A767",
        "900": "#B4916C",
        DEFAULT: "#6B089C",
      },
      dark: {
        "100": "#ccc",
        "150": "#00000080",
        "200": "#D3CDC7",
        "300": "#B9B9B9",
        "400": "#939CAB",
        "450": "#808080",
        "500": "#626262",
        "600": "#444444",
        "700": "#383838",
        "800": "#222222",
        "900": "#242424",
        DEFAULT: "#242424",
      },
      white: {
        "200": "#EBEBEB",
        "300": "#F5F5F5",
        "400": "#E8E7E7",
        "500": "#E7E7E7",
        "600": "#f2f2f2",
        "700": "#D9D9D9",
        "800": "#F9F9F9",
        "900": "#F5F5F5",
        DEFAULT: "#FFFFFF",
      },
      yellow: {
        "100": "#5F370E",
        "200": "#713F12",
        "300": "#854D0E",
        "400": "#A16207",
        "500": "#CA8A04",
        "600": "#EAB308",
        "700": "#FACC15",
        "800": "#FDE047",
        "900": "#F5CF05",
        DEFAULT: "#F9A825",
      },
      red: {
        "100": "#FECACA",
        "200": "#FCA5A5",
        "300": "#FA6338",
        "400": "#F87171",
        "500": "#EB5757",
        "600": "#DC2626",
        "700": "#CF5763",
        "800": "#E01020",
        "900": "#FC2B2B",
        DEFAULT: "#FC2B2B",
      },
      blue: {
        "100": "#BFDBFE",
        "200": "#93C5FD",
        "300": "#60A5FA",
        "400": "#3B82F6",
        "500": "#33496C",
        "600": "#2563EB",
        "700": "#1D4ED8",
        "800": "#0089ED",
        "900": "#1E3A8A",
        DEFAULT: "#0089ED",
      },
      gray: {
        "100": "#F3F4F6",
        "200": "#E5E7EB",
        "300": "#D1D5DB",
        "400": "#9CA3AF",
        "500": "#6B7280",
        "600": "#4B5563",
        "700": "#374151",
        "800": "#1F2937",
        "900": "#111827",
        DEFAULT: "#939CAB",
      },
      green: {
        "100": "#DCFCE7",
        "200": "#D1FAE5",
        "300": "#BBF7D0",
        "400": "#86EFAC",
        "500": "#4ADE80",
        "600": "#22C55E",
        "700": "#15803D",
        "800": "#166534",
        "900": "#14532D",
        DEFAULT: "#15803D",
      },
    },
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
      },
      fill: {
        hover: {
          blue: "#4299e1",
          red: "#f56565",
        },
      },
      keyframes: {
        fadeInDown: {
          "0%": {
            top: "50%",
            opacity: "0",
          },
          "100%": {
            top: "100%",
            opacity: "1",
          },
        },
        fadeInUp: {
          "0%": {
            bottom: "50%",
            opacity: "0",
          },
          "100%": {
            bottom: "100%",
            opacity: "1",
          },
        },
        changeColor: {
          "0%": {
            backgroundSize: "0 100%",
            backgroundColor: "#B9B9B9",
          },
          "100%": {
            backgroundSize: "100% 100%",
            backgroundColor: "#B4916C",
          },
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
    },
  },
  variants: {
    fill: ["hover"],
  },
  plugins: [require("tailwindcss-animate"), require("daisyui")],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  },
};

export default config;
